---
- name: Update apt cache.
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install OpenJDK packages.
  package:
    name: "{{ openjdk_packages }}"
    state: present

- name: Default-java symlink
  file:
    path: "{{ openjdk_default_java_link }}"
    src: "{{ openjdk_java_full_path }}"
    state: link
    force: true
